### ISSUE TITLE
FTBFS without libConfuse or --without-config (master)

### ISSUE THREAD

**Issue by pioneerAlone** [troglobit/merecat#10]
Using master v2.32, 
autogen.sh
build.sh
 the following problem occurs
CC       merecat-base64.o
 CC       merecat-md5.o
  CC       merecat-merecat.o
  CC       merecat-mmc.o
  CC       merecat-pidfile.o
In file included from merecat.c:52:0:
conf.h: In function ‘conf_srv’:
conf.h:88:16: error: ‘do_ssl’ undeclared (first use in this function)
  arr[0].ssl  = do_ssl;
                ^
conf.h:88:16: note: each undeclared identifier is reported only once for each function it appears in
Makefile:563: recipe for target 'merecat-merecat.o' failed
make[2]: *** [merecat-merecat.o] Error 1

**Comment by troglobit** [comment]
To debug that I need your config.log file. It looks like a missing `#ifndef ENABLE_SSL`.  In the meantime, try installing libssl-dev,

**Comment by troglobit** [comment]
Ah, now I see!  Seems I've forgot to update the code path when you build without support for `mercat.conf`.  I.e., `configure --without-config`, or when the configure script cannot find libConfuse installed.  Good, find thanks!

**Comment by troglobit** [comment]
There, latest master now has a fix for this issue. I've also updated the README with the build requirements to unlock HTTPS support (by installing libConfuse-dev).
