### ISSUE TITLE
Compile options for Raspberry Pi 

### ISSUE THREAD

**Issue by icoris** [troglobit/merecat#13]
Hi,

I'm trying to run Merecat on a Raspberry Pi nano to host a hugo site. 
Following you instructions on Github, I compiled Merecat and installed it into /usr/sbin. Then after setting up merecat.conf to use HTTPS and HTTP. I ran Merecat using systemctl.

The only problem that I am finding with Merecat is that it is taking up 100% CPU on the Raspberry Pi nano. Is there any compile options that could be used to optimize Merecat for Raspberry PI?

Thanks in advance for any help that you can provide.

**Comment by troglobit** [comment]
There is a regression right now on the master branch that I need to fix.  Otherwise it should not take 100% CPU, not even on an RPi Nano.

I'll get back to you soon (a day or two) with an update.

**Comment by troglobit** [comment]
Commit a5d54d9, pushed just now, should fix the regression I've seen in my production system.  

Depending on your use-case, you can add the following options to the configure script to reduce size and impact.  See `configure --help` for details.

```
--without-config
--without-ssl
--without-zlib
```

**Comment by icoris** [comment]
Thank you for your help the new version works better!

**Comment by troglobit** [comment]
Awesome, then I'll be closing this issue then :)

Please feel free to open new issues if you have more questions. I also have an IRC channel on FreeNode.
