### ISSUE TITLE
Wrong OpenSSL version

### ISSUE THREAD

**Issue by vojta7** [troglobit/merecat#14]
The current master requires OpenSSL version 1.1.0, but [TLS1_3_VERSION](https://github.com/troglobit/merecat/blob/a5d54d9dde923b9b46c16adf439cca70eef90da2/src/ssl.c#L61) and [SSL_CTX_set_ciphersuites](https://github.com/troglobit/merecat/blob/a5d54d9dde923b9b46c16adf439cca70eef90da2/src/ssl.c#L195) seem to be available up from version 1.1.1.

**Comment by troglobit** [comment]
Good catch, I'll look into fixing it, thanks!

**Comment by troglobit** [comment]
Again, thank you for reporting this! :-)

**Comment by vojta7** [comment]
You are welcome :)
