### ISSUE TITLE
python cgi

### ISSUE THREAD

**Issue by pioneerAlone** [troglobit/merecat#15]
How to make it support python cgi

**Comment by troglobit** [comment]
Hi!  There's no difference between running a Python CGI application and a Bourne shell script,
as mentioned here https://troglobit.com/2019/08/Basic-CGI-in-C-with-Merecat-httpd/

Make sure to place the Python script in the cgi-bin directory you've set in your merecat.conf,
*and* that the script has the executable bit set.

Also, make it work *without* chroot first.

**Comment by pioneerAlone** [comment]
Yes, I have succeeded, and may start because of the format.

**Comment by troglobit** [comment]
OK, good!  So we can close this issue then?

**Comment by troglobit** [comment]
No reply from reported, closing.
