### ISSUE TITLE
index.php does not run in subfolders

### ISSUE THREAD

**Issue by ricardoG08** [troglobit/merecat#21]
See #17 for a background.

**Comment by troglobit** [comment]
Replicated here, both with and without any GET request arguments (issue #22) it fails with a 403.

**Comment by troglobit** [comment]
There, should work a lot better now!  The internal is_php() function checked the URL, not the expanded filename, so lost the `index.php` filled in earlier in the processing.

Thank you for reporting this, and hanging in there waiting for my getting the time to fix it <3
