### ISSUE TITLE
PHP with method GET does not work

### ISSUE THREAD

**Issue by ricardoG08** [troglobit/merecat#22]
Mercat returns error 403 for a valid URL, for example:

http://localhost?page=home

the POST method works fine and also the GET method without the symbol "?", for example:

http://localhost/index.php

**Comment by troglobit** [comment]
This *should* be fixed now, I've even added a simple unit test for it.  If you get the chance to verify I'd appreciate feedback so we could close this.

Thank you for reminding me today, and actually helping unlock this one! :)

**Comment by ricardoG08** [comment]
problem fixed, GET methods work fine
