### ISSUE TITLE
build time issues with php support

### ISSUE THREAD

**Issue by joostvb-gh** [troglobit/merecat#29]
Hi,

I just tried to build merecat Merecat httpd 2.32-rc4 as it sits in git today, on a Debian oldstable 10/buster system.
I don't have php-cgi installed.  I tried to build a Debian package from it: I invoked 'debuild' from the merecat
git checkout.  It failed with:

```
make[3]: Entering directory '/home/joostvb/git-ro/merecat/tests'
/usr/bin/make  check-TESTS
make[4]: Entering directory '/home/joostvb/git-ro/merecat/tests'
make[5]: Entering directory '/home/joostvb/git-ro/merecat/tests'
PASS: start.sh
PASS: cgi.sh
FAIL: php.sh
PASS: gzip.sh
PASS: redirect.sh
PASS: location.sh
PASS: stop.sh
============================================================================
Testsuite summary for Merecat httpd 2.32-rc4
============================================================================
# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to https://github.com/troglobit/merecat/issues
============================================================================
make[5]: *** [Makefile:486: test-suite.log] Error 1
```

.

test-suite.log has:
```
FAIL: php
=========

+ echo <?php echo 'Hello ' . htmlspecialchars($_GET["name"]) . '!'; ?>
+ ls srv
cgi-bin
img
index.html
index.html.gz
main.css
main.css.gz
test.php
+ cat srv/test.php
<?php echo 'Hello ' . htmlspecialchars($_GET["name"]) . '!'; ?>
+ + curl http://localhost:8086/test.php?name=foobar
grep Hello foobar
FAIL php.sh (exit status: 1)
```

It would be nice if in debian/control, the line

Build-Depends: debhelper (>= 10), systemd, pkg-config, libconfuse-dev, libssl-dev, zlib1g-dev

could be replaced with

Build-Depends: debhelper (>= 10), systemd, pkg-config, libconfuse-dev, libssl-dev, zlib1g-dev, php7.4-cgi | php-cgi

(I didn't test that, btw).  Furthermore, it'd be nice if ./configure honoured a --disable-php flag.

Thanks for maintaining merecat!

Bye,

Joost

**Comment by troglobit** [comment]
Hi,

PHP is not a build-time dependency, is a configuration option.  So if you have  /usr/bin/php-cgi installed you can use it just like any type of CGI.  That's why it's not in Build-depends or has a configure option.  I guess a Build-recommends or -suggests could be in order, if that exists, I dunno.  I've only whipped up that `debian/` build directory for my own benefit and to facilitate testing before the next release.

So ... I'm going to close this with a "won't fix" tag, unfortunately.  Thanks for using Merecat! <3
