### ISSUE TITLE
make dist; make check fails: fatal: making test-suite.log: failed to create php.trs

### ISSUE THREAD

**Issue by joostvb-gh** [troglobit/merecat#31]
Hi,

After creating a tarball from a fresh git checkout with 'make distcheck', unpacking that tarball and running "make check", the
tests fail with 

fatal: making test-suite.log: failed to create php.trs
fatal: making test-suite.log: failed to create php.log
make[4]: *** [Makefile:487: test-suite.log] Error 1

This is likely due to tests/php.sh not being included in the tarball.  I believe this could be fixed by adding
php.sh to EXTRA_DIST in tests/Makefile.am.

Thanks!

Bye, Joost

**Comment by troglobit** [comment]
Yep, looks like it.  Care to do a pull request? :-)

**Comment by joostvb-gh** [comment]
The one-line patch would take me half an hour to get through this github webui.  I'd rather not, now...

Thanks a lot!

**Comment by troglobit** [comment]
Fixed in #33

**Comment by troglobit** [comment]
Thanks! :)
