### ISSUE TITLE
Skip doc installation

### ISSUE THREAD

**Issue by tieugene** [troglobit/merecat#37]
There must be possible to skip doc installation.
I'm trying to build rpm for Fedora Linux. It packs documentation and licenses with its own commands:
```spec
%files
%license LICENSE
%doc README.md ChangeLog.md
```
So I have to delete installed `/usr/share/doc/merecat/LICENSE` during packaging because
`Extra file[s] installed but not packed: /usr/share/doc/merecat/LICENSE`
Other 2 doc files are installing into the same folder as `rpmbuild` uses, but it its coincidence and unreliably.

**Comment by troglobit** [comment]
No, this is a downstream packaging issue.  We as upstream cannot take every possible packaging tool into account when maintaining our project.   Marking this wontfix

It is not at all uncommon that OSS packages install their license as part of the documentation. In fact, I'd venture to say it's the norm.  Also, all configure based programs already support various `make install-foo` sub-targets that can be used to achieve what you're asking for.

Glancing at https://rpm-software-management.github.io/rpm/manual/spec.html, I suggest using `%doc` also for license, or drop the file in the `%install` step instead.

**Comment by tieugene** [comment]
> Also, all configure based programs already support various `make install-foo` sub-targets that can be used to achieve what you're asking for.

`./configure --without-doc` not works.

>  suggest using %doc also for license, or drop the file in the %install step instead.

Putting license into %doc is not good idea, but removing license in %install is the thing that I do now.

**Comment by troglobit** [comment]
Like I said, won't fix.  So no need to comment on this further, the matter is closed.  Every integration in an end-user system requires some sort of workaround or adaptation to that system, this is the responsibility of the packager.
