### ISSUE TITLE
Allow cross origin header

### ISSUE THREAD

**Issue by thenoobtester** [troglobit/merecat#40]
Hi,

thank you for this great piece of software. I need to add the Access-Control-Allow-Origin header to the response headers and i just can't figure out how to do it.

Could you please help me ?

Thank you very much

**Comment by troglobit** [comment]
You can have a look at `send_mime()`, it is called from `httpd_start_request()`.  Good luck! https://github.com/troglobit/merecat/blob/606774ec856f4015e472ed5e441de94e11722988/src/libhttpd.c#L753-L755

**Comment by thenoobtester** [comment]
Thank you for the quick response. To make sure i understand your response, do you mean it cannot be done out-of-the-box and that I should modify the source code? If that's the case then I'm afraid it's out of my skills :( I was hoping there would be an option or something.

Thank you

**Comment by troglobit** [comment]
Correct, you need to patch the code.

**Comment by thenoobtester** [comment]
As a quick follow-up. I added the following line to the `send_mime()` function from the [merecat/src/libhttpd.c](https://github.com/troglobit/merecat/blob/606774ec856f4015e472ed5e441de94e11722988/src/libhttpd.c#L753-L755) file you mentionned:

`"Access-Control-Allow-Origin: *\r\n",`

Before:

```
			 "Last-Modified: %s\r\n"
			 "Accept-Ranges: bytes\r\n",
			 hc->protocol, status, title, nowbuf, EXPOSED_SERVER_SOFTWARE, modbuf);
```

After:

```
			 "Last-Modified: %s\r\n"
			 "Accept-Ranges: bytes\r\n"
			 "Access-Control-Allow-Origin: *\r\n",
			 hc->protocol, status, title, nowbuf, EXPOSED_SERVER_SOFTWARE, modbuf);
```

It now adds the Access-Control-Allow-Origin: * header to every response, so ideally I would add it as a configurable parameter with a regex to target specific files (like they did here on another project https://github.com/monkey/monkey/commit/d4d4dab07a8165e748793de7da998de19710ef9e) and choose if I allow any origin with * or be more specific. But that's for later as I'm no pro programmer and C is hard.

Thank you for your help and directing me in the right direction.
