### ISSUE TITLE
Performance issues ?

### ISSUE THREAD

**Issue by ArthurPons** [troglobit/merecat#44]
Hi !

I've been using merecat for a community managed server that serves multiple vhosts : http://bebou.netlib.re
Easy to setup, everything works great except we've been having some strange performance issues. I'm having a lot of trouble understanding what's happening.

The symptoms and what I know : 

  * A few KB of data take more than one second to download. For example http://arthur.bebou.netlib.re might take 1.5 seconds to load even though it is a fairly lightweight page.
  * When someones streams audio from http://doublezip.bebou.netlib.re/ htop shows merecat using 100% of one of the servers CPU.
  * On http://doublezip.bebou.netlib.re the video dj.webm, by far the largest element in the page, loads almost instantly but the far smaller html document loads in more than one second.
  * While audio is streamed it is almost impossible to access other resources.
  * RAM usage is fine
  * When tested with busybox's httpd everything works fine, pages load instantly and streaming audio uses a minuscule amount of CPU. But I want vhosts :(
  * pretty much nothing else is happening on the server other than from serving web pages
  * running merecat not chrooted and serving a single host doesn't change anything

My setup : 

  * raspberry 3b running up-to date raspberry os
  * merecat installed via debian packages
  * great internet connection, can't be the problem
  * client side tests done in up-to date firefox and chromium packaged by debian
  * merecat launched with `systemctl start merecat.service`, everything looks right in journalctl

I'm having trouble understanding what's happening and I'm not sure how to effectively troubleshoot on the server. It *feels* like merecat or something on the server imposes an arbitrary ~1.2 seconds delay to a bunch of resources. I may very well be missing something obvious.

Thank you for your time, have a nice day :)

My merecat config : 

```
## /etc/merecat.conf                                     -*-conf-unix-*-
## This is a sample configuration file for Merecat httpd
## For more help and more settings, see merecat.conf(5).
##

## what interface to bind to?
## (default is binding to any interface)
#hostname=www.example.org

## Port to listen to, overrides command line argument
## Defaults to 80, or 443 when enabling HTTPS
port = 80

## Unpriviliged user to run as, usually nobody or www-data
#username = nobody

## Global .htpasswd (true) or local per-directory (false)
#global-passwd = false

## Chrooting is a security measure which means isolating the webserver's
## access to files only available from a the given directory.  To access
## files outside the chroot the administrator can either copy or bind
## mount files and directories into the chroot.
chroot = true

## Only useful if not chrooting
#check-symlinks = false

## Alt. charset=iso-8859-1
charset = UTF-8

## Deflate (gzip) compression level: -1 .. 9
## -1: Default (zlib's reasonable default, currently 6)
##  0: Disabled
##  1: Best speed
##  9: Best compression
#compression-level = -1

## Webserver document root, or chroot
directory = /var/www

## When chrooting, alt. document root inside chroot
## => /var/www/htdocs
# data-directory = htdocs

## Skip dotfiles in dirlistings
#list-dotfiles = false

## Virtual hosting
## /var/www/cgi-bin/          <-- Shared CGI
## /var/www/meso.bebou.netlib.re
virtual-host = true

## Control the caching, in seconds, by setting the following header for
## all transactions.  Depends heavily on the content you provide, and
## this global setting is disabled by default.  It is recommended to
## instead set it per server location, e.g. for all image files.
##
##    Cache-Control: max-age=SEC
##
## Min max-age value 0 (browser caching disabled)
## Max max-age value 31536000 (1 year)
##
max-age = 3600

## Some bots behave really badly and may overload your server.  Often
## they cannot be blocked based on IP address, so the only means we are
## left with is User-Agent blocking.  Use patterns like this:
#user-agent-deny = "**SemrushBot**|**MJ12bot**|**DotBot**|**PetalBot**"

## Enable HTTPS support.  The certificate (public) and key (private) are
## required when enabling HTTPS support.  The (min) protocol and cipher
## settings are optional and have sane built-in defaults, e.g. 'protocol'
## defaults to TLSv1.1.  See ciphers(1) man page for possible values.
##
## Note: You may want to enable this on a per-server basis instead.
#ssl {
#    protocol = "TLSv1.1"
#    ciphers  = "..."
#    certfile = certs/cert.pem
#    keyfile  = private/key.pem
#    dhfile   = certs/dhparam.pem
#}

## The CGI module is a core part of Merecat httpd and is for security
## reasons disabled by default.  Like other modules it uses pattern
## matching to trigger the CGI functionality:
##	?	match a single char
##	*	matches any string excluding "/"
##	**	matches any string including "/"
##	separate multiple patterns with "|"
## Example: "**.sh|**.cgi"
##
## `limit` sets the max number of simultaneous CGI programs allowed.
##
## The below values are the default, so to enable CGI only `enabled`
## need to be set to 'true'.
#cgi "**.cgi|/cgi-bin/*" {
#    enabled = false
#    limit   = 50
#}

## The PHP module is bolted on top of the CGI module, so the same limits
## apply also to PHP scripts.  The below are the built-in defaults.
## Verify the path to the php-cgi binary for your system and expand on
## the pattern if you have, e.g. .php5 files.
#php "**.php*" {
#    enabled  = false
#    cgi-path = "/usr/bin/php-cgi"
#}

## The SSI module, like PHP above, is built on top of the CGI module,
## and it also requires the Merecat SSI CGI script to be installed, the
## defaults are commented out below.  The silent setting controls the
## default <!--#config errmsg="..." --> value.
#ssi "**.shtml" {
#    enabled  = false
#    silent   = false
#    cgi-path = "cgi-bin/ssi"
#}

## Server specific settings, overrides certain global settings
## Notice the HTTP redirect from the default server to HTTPS.
server default {
     port = 80
}

#server secure {
#    port = 443
#    ssl {
#	certfile = letsencrypt/cert.pem
#	keyfile = letsencrypt/privkey.pem
#	dhfile = certs/dhparam.pem
#    }
#}
```

**Comment by troglobit** [comment]
Merecat is/was a personal project and idea I have/had of extending thttpd with native HTTPS support, and some other neat features for embedded systems.  I've never managed to finish it, nor did I ever get anyone to help out with the coding, so there's no official release with all this yet, although I know there are people using it. 

The thttpd web server is a *throttling* web server, and it sounds like that's what you're running into.  Maybe that keyword can help you dig further on your own because I have no time to help you out.

**Comment by ArthurPons** [comment]
Understood, I'll dig into thttpd.
If I find anything conclusive I'll make it known in case some people stumble upon the same issue.

Have a nice day !
