### ISSUE TITLE
libconfuse2

### ISSUE THREAD

**Issue by Zibri** [troglobit/merecat#8]
configure: error: Package requirements (libconfuse >= 2.7) were not met:

No package 'libconfuse' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables confuse_CFLAGS
and confuse_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

---- my system is ubuntu 18.04

dpkg -l |grep confuse
ii  libconfuse-common                    3.2.1+dfsg-4ubuntu0.1                       all          Common files for libConfuse
ii  libconfuse-dev:amd64                 3.2.1+dfsg-4ubuntu0.1                       amd64        Development files for libConfuse
ii  libconfuse-doc                       3.2.1+dfsg-4ubuntu0.1                       all          Documentation for libConfuse
ii  libconfuse2:amd64                    3.2.1+dfsg-4ubuntu0.1                       amd64        Library for parsing configuration files

**Comment by troglobit** [comment]
I run Ubuntu 19.04:

```sh
jocke@luthien:~/Troglobit/merecat [master]$ dpkg -l |grep confuse
ii  libconfuse-common                          3.2.2+dfsg-1                               all          Common files for libConfuse
ii  libconfuse-dev:amd64                       3.2.2+dfsg-1                               amd64        Development files for libConfuse
ii  libconfuse-doc                             3.2.2+dfsg-1                               all          Documentation for libConfuse
ii  libconfuse2:amd64                          3.2.2+dfsg-1                               amd64        Library for parsing configuration files
```

What version of Merecat are you using?  Building from the latest GIT master seems to work for me. (Yeah, it's been a while since the last release. I haven't had time to finalize and test the new HTTPS and multiple server support. Sorry)

**Comment by Zibri** [comment]
I tried to compile it from the git version on Ubuntu 18.04 (not 19..
that was a typo)

**Comment by troglobit** [comment]
OK, I've found an 18.04 install now and tested building Merecat from the lastet git master. Works there too:

```
...
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for confuse... yes
...
```

Maybe your system is missing `pkg-config`?

**Comment by Zibri** [comment]
nope.
$ pkg-config --version
0.29.1

**Comment by Zibri** [comment]
after ./autogen.sh
I did ./configure
and got:

$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether ln -s works... yes
checking for ar... ar
checking for crypt in -lcrypt... yes
checking for clock_gettime in -lrt... yes
checking for hstrerror in -lresolv... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking for memory.h... (cached) yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking osreldate.h usability... no
checking osreldate.h presence... no
checking for osreldate.h... no
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/devpoll.h usability... no
checking sys/devpoll.h presence... no
checking for sys/devpoll.h... no
checking sys/event.h usability... no
checking sys/event.h presence... no
checking for sys/event.h... no
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/poll.h usability... yes
checking sys/poll.h presence... yes
checking for sys/poll.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking whether time.h and sys/time.h may both be included... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for ranlib... ranlib
checking for uid_t in sys/types.h... yes
checking for int64_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for unistd.h... (cached) yes
checking for working chown... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether lstat correctly handles trailing slash... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... yes
checking for working mmap... yes
checking for wait3 that fills in rusage... yes
checking for alarm... yes
checking for atoll... yes
checking for clock_gettime... yes
checking for daemon... yes
checking for dup2... yes
checking for gai_strerror... yes
checking for getcwd... yes
checking for getaddrinfo... yes
checking for gethostbyname... yes
checking for gethostname... yes
checking for getnameinfo... yes
checking for getpass... yes
checking for gettimeofday... yes
checking for hstrerror... yes
checking for inet_ntoa... yes
checking for kqueue... no
checking for malloc... yes
checking for memmove... yes
checking for memset... yes
checking for mkdir... yes
checking for munmap... yes
checking for poll... yes
checking for select... yes
checking for setlogin... no
checking for setsid... yes
checking for sigaction... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strcspn... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for tzset... yes
checking for snprintf... yes
checking for waitpid... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for confuse... no
configure: error: Package requirements (libconfuse >= 2.7) were not met:

No package 'libconfuse' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables confuse_CFLAGS
and confuse_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by Zibri** [comment]
it works on Ubuntu desktop 17.10  is on ubuntu server 18.04 that it has problems for some reason.

**Comment by Zibri** [comment]
celarle there is something missing in ubuntu server 18.04 not directly your fault.. but the server was cleanly installed... I have no clue

**Comment by troglobit** [comment]
Yeah, probably.  Have you tried reinstalling the libconfuse-dev package and verify that the contents of `/usr/lib/x86_64-linux-gnu/pkgconfig/libconfuse.pc` says:

```
...
Name: confuse
Version: 3.2.1
...
```

Maybe I can find something more if you attach the config.log file ...

**Comment by troglobit** [comment]
Ping?

**Comment by troglobit** [comment]
I'm pretty sure I found it, finally.
