### ISSUE TITLE
Installation method is not detailed enough

### ISSUE THREAD

**Issue by pioneerAlone** [troglobit/merecat#9]
Can the program be cross-compiled with arm and related configuration methods and procedures?

**Comment by troglobit** [comment]
Hi, happy to see someone is interested in Merecat :-)

Yes, with some limitations.  It's a standard GNU configure based system so if you set `--host` to your cross-compiler tuple it should work.  I've been using it in my qemu-based embedded system, TroglOS.  For more info on how I've integrated it there, see here: https://github.com/troglobit/troglos/blob/master/packages/merecat/Makefile

Note: the latest GIT master (upcoming v2.32) is *not yet* intended for production.  Hopefully will be in a couple of weeks when I've finalized testing of HTTPS.  I will update the README with more details on how to build and cross-compile before releasing v2.32.

**Comment by pioneerAlone** [comment]
thanks！

**Comment by pioneerAlone** [comment]
Hello, merecat is already installed in ubuntu, I want to know how to test and what is the basic configuration of merecat.conf

**Comment by pioneerAlone** [comment]
Hello, merecat is already installed in ubuntu, I want to know how to test and what is the basic configuration of merecat.conf

**Comment by troglobit** [comment]
That depends highly on what version of Merecat you are running, but for both the released v2.31 and the yet _unreleased_ v2.32 (GIT master) the accompanying documentation details all features that are available:

   * README.md
   * merecat.8 
   * merecat.conf

> **Note:** read the documentation of the _installed_ version.  The documentation on GitHub is for the yet unreleased v2.32.

The man page has split into two on GIT master, merecat.8 and merecat.conf.5.  To read them, use:

    $ man 8 merecat

and, if you are using GIT master version

    $ man 5 merecat.conf

The sample `merecat.conf` file that is included in all releases contains all available settings, usually with the default value commented out.  For details on each setting, see the man page.
